theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-pairs = true
completion-replace = true
completion-trigger-len = 1
shell = ["dash", "-c"]

[editor.lsp]
enable = true

[editor.auto-save]
focus-lost = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["spinner", "mode"]
center = ["read-only-indicator", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
