theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-pairs = true
completion-trigger-len = 1
shell = ["dash", "-c"]
bufferline = "always"

[editor.lsp]
enable = true

[editor.auto-save]
focus-lost = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["spinner", "mode"]
center = ["read-only-indicator", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.smart-tab]
enable = true

[[language]]
name = "__common__"
scope = "source.__common__"
file-types = []
language-servers = ["lsp-ai"]

[language-server.lsp-ai]
command = "lsp-ai"
