when:
  - event: pull_request_closed
    branch: auto-update

  - event : cron
    cron: weekly-update

steps:
  - name: nix flake update
    image: nixos/nix:latest
    pull: true
    commands:
      - nix flake update --extra-experimental-features nix-command --extra-experimental-features flakes

  - name: push flake commit
    image: appleboy/drone-git-push
    settings:
      branch: auto-update
      local_ref: auto-update
      remote_name: origin
      force: false
      commit: true

  - name: create pull request
    image: johnwalkerx/gitea-pull-request-create-plugin:latest
    pull: true
    settings:
      gitea_address: https://git.litelot.us
      gitea_token:
        from_secret: automation-token
      owner: ${CI_REPO_OWNER}
      repo: ${CI_REPO_NAME}
      base_branch: main
      branch: auto-update
      pr_title: Nix Flake Upgrade
      pr_body: |
        Automated Nix Flake upgrade
        Ran At: ${CI_PIPELINE_STARTED}
        Triggered By: ${CI_PIPELINE_EVENT}
      close_pr_if_empty: true
