when:
  - event: push
    branch: main

steps:
  - name: create sync pr
    image: johnwalkerx/gitea-pull-request-create-plugin:latest
    pull: true
    settings:
      gitea_address: https://git.litelot.us
      gitea_token:
        from_secret: automation-token
      owner: ${CI_REPO_OWNER}
      repo: ${CI_REPO_NAME}
      base_branch: auto-update
      branch: main
      pr_title: Automation Branch Update
      pr_body: |
        Automated branch sync
        Ran At: ${CI_PIPELINE_STARTED}
        Triggered By: ${CI_PIPELINE_EVENT}
      close_pr_if_empty: true
      merge_when_checks_succeed: true
      
